### ISSUE TITLE
Unable to install skype-api - npm (with Meteor js)

### ISSUE THREAD

**Issue by ravipatel123** [vslinko/skype-api#1]
Hello,
I am using Meteor js.
I am trying to install this package install
my system configuration
node v0.12.4
 npm  v2.10.1
I have install all the dependency, done lot of googling, but still unable to install this package.

npm install --save skype-api@^0.2
# but getting below error

> node-gyp rebuild

make: Entering directory `/home/cis/Desktop/meteor_workspace/myProject-meteor/node_modules/skype-api/node_modules/zerorpc/node_modules/msgpack/build'
  CXX(target) Release/obj.target/libmsgpack/deps/msgpack/gcc_atomic.o
  CXX(target) Release/obj.target/libmsgpack/deps/msgpack/object.o
In file included from ../deps/msgpack/msgpack/type/fixint.hpp:22:0,
                 from ../deps/msgpack/msgpack/type.hpp:3,
                 from ../deps/msgpack/msgpack/object.hpp:418,
                 from ../deps/msgpack/object.cpp:18:
../deps/msgpack/msgpack/type/int.hpp: In static member function ‘static void msgpack::type::detail::object_char_sign<true>::make(msgpack::object&, char)’:
../deps/msgpack/msgpack/type/int.hpp:102:22: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
../deps/msgpack/msgpack/type/int.hpp: In function ‘void msgpack::operator<<(msgpack::object&, signed char)’:
../deps/msgpack/msgpack/type/int.hpp:206:76: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
../deps/msgpack/msgpack/type/int.hpp: In function ‘void msgpack::operator<<(msgpack::object&, short int)’:
../deps/msgpack/msgpack/type/int.hpp:209:76: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
../deps/msgpack/msgpack/type/int.hpp: In function ‘void msgpack::operator<<(msgpack::object&, int)’:
../deps/msgpack/msgpack/type/int.hpp:212:76: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
../deps/msgpack/msgpack/type/int.hpp: In function ‘void msgpack::operator<<(msgpack::object&, long int)’:
../deps/msgpack/msgpack/type/int.hpp:215:76: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
../deps/msgpack/msgpack/type/int.hpp: In function ‘void msgpack::operator<<(msgpack::object&, long long int)’:
../deps/msgpack/msgpack/type/int.hpp:218:76: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
In file included from ../deps/msgpack/msgpack/type.hpp:3:0,
                 from ../deps/msgpack/msgpack/object.hpp:418,
                 from ../deps/msgpack/object.cpp:18:
../deps/msgpack/msgpack/type/fixint.hpp: In function ‘void msgpack::operator<<(msgpack::object&, msgpack::type::fix_int8)’:
../deps/msgpack/msgpack/type/fixint.hpp:118:88: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
In file included from ../deps/msgpack/msgpack/type.hpp:3:0,
                 from ../deps/msgpack/msgpack/object.hpp:418,
                 from ../deps/msgpack/object.cpp:18:
../deps/msgpack/msgpack/type/fixint.hpp: In function ‘void msgpack::operator<<(msgpack::object&, msgpack::type::fix_int16)’:
../deps/msgpack/msgpack/type/fixint.hpp:121:88: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
../deps/msgpack/msgpack/type/fixint.hpp: In function ‘void msgpack::operator<<(msgpack::object&, msgpack::type::fix_int32)’:
../deps/msgpack/msgpack/type/fixint.hpp:124:88: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
../deps/msgpack/msgpack/type/fixint.hpp: In function ‘void msgpack::operator<<(msgpack::object&, msgpack::type::fix_int64)’:
../deps/msgpack/msgpack/type/fixint.hpp:127:88: warning: enumeral and non-enumeral type in conditional expression [enabled by default]
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/objectc.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/unpack.o
../deps/msgpack/unpack.c: In function ‘template_callback_root’:
../deps/msgpack/unpack.c:59:1: warning: missing initializer [-Wmissing-field-initializers]
../deps/msgpack/unpack.c:59:1: warning: (near initialization for ‘o.type’) [-Wmissing-field-initializers]
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/vrefbuffer.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/zone.o
  CC(target) Release/obj.target/libmsgpack/deps/msgpack/version.o
  AR(target) Release/obj.target/deps/msgpack/msgpack.a
  COPY Release/msgpack.a
  CXX(target) Release/obj.target/msgpackBinding/src/msgpack.o
  SOLINK_MODULE(target) Release/obj.target/msgpackBinding.node
  SOLINK_MODULE(target) Release/obj.target/msgpackBinding.node: Finished
  COPY Release/msgpackBinding.node
make: Leaving directory`/home/cis/Desktop/meteor_workspace/myProject-meteor/node_modules/skype-api/node_modules/zerorpc/node_modules/msgpack/build'
npm ERR! Linux 3.5.0-23-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "skype-api@^0.2"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.12.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.12.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cis/Desktop/meteor_workspace/myProject-meteor/npm-debug.log
cis@cism123:~/Desktop/meteor_workspace/myProject-meteor$ npm install zmq
\

> zmq@2.12.0 install /home/cis/Desktop/meteor_workspace/myProject-meteor/node_modules/zmq
> node-gyp rebuild

make: Entering directory `/home/cis/Desktop/meteor_workspace/myProject-meteor/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory`/home/cis/Desktop/meteor_workspace/myProject-meteor/node_modules/zmq/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.5.0-23-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/cis/Desktop/meteor_workspace/myProject-meteor/node_modules/zmq
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.5.0-23-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "zmq"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.12.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.12.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
# npm ERR!     /home/cis/Desktop/meteor_workspace/myProject-meteor/npm-debug.log

**Comment by vslinko** [comment]
Hello!

Thank you for your issue, but I can't help you for these reasons:
- Main problem is in `zmq` dependency.
- Current project is archived and have no maintainer.
- Microsoft closed support of Skype API.

**Comment by johnRivs** [comment]
So, is this project dead?

**Comment by vslinko** [comment]
Yes, it is dead.
